export const OXYTOCIN_FORM_CONCEPTS = {
  time: '160632AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  oxytocinDropsPerMinute: '166531AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
} as const;
export const CERVIX_FORM_CONCEPTS = {
  hour: '159682AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  time: '160632AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  cervicalDilation: '162261AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  descentOfHead: '159682AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
} as const;
